"""Cross-language state.json round-trip — PLAN.md cutover criterion #2.

`agents/{adw_id}/state.json` is the sole cross-language contract between the
Python `adw/` pipeline and the TypeScript `adw_sdlc/` engine (PLAN.md D4). With
no shared code across the language boundary, the only thing that keeps two
reimplementations from drifting is a contract tested from *both* sides. These
tests are the Python half; `adw_sdlc/test/cross-language-state.test.ts` is the
twin. Together they prove the three sub-criteria of cutover criterion #2:

  (i)   both engines' `state.json` validate against `adw/state.schema.json`;
  (ii)  a TS-engine-produced `state.json` is loadable+resumable by Python
        `AdwState.load()` (and the Python-produced fixture is the input the TS
        suite loads from its own side — the "and vice-versa" half);
  (iii) the two engines' documents agree on every v1 field, differing only by
        the TS-additive keys (`engine`/`runner`/`total_cost_usd`) which the
        Python reader drops (they are never load-bearing for resume).

The committed fixtures live in `adw/fixtures/cross_language/` — the shared
contract directory, next to `state.schema.json`. A drift guard regenerates the
Python fixture from the *real* writer so it can never silently rot; the
ts-produced fixture is regenerated by the TS suite's twin drift guard. Both
fixtures encode the *same logical run* (same `adw_id`, same v1 values), so the
v1 projection of one must equal the v1 projection of the other.
"""

from __future__ import annotations

import json
import tempfile
import unittest
from dataclasses import fields
from pathlib import Path
from unittest import mock

from adw import _state
from adw._state import AdwState

# Reuse the Python half of the schema validator (the same helper test_state.py
# uses for the drift guard) so the cross-language fixtures are checked against
# the very same subset validator, not a second hand-rolled copy.
from adw.test_state import SCHEMA_PATH, _validate

FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "cross_language"
PY_FIXTURE = FIXTURE_DIR / "py-produced-state.json"
TS_FIXTURE = FIXTURE_DIR / "ts-produced-state.json"

# The canonical run id both fixtures share (a valid 8-char hex id).
ADW_ID = "00000000"

# The full ordered phase-completion list of a finished run: setup (control) +
# the nine agent phases in AGENT_PHASES order + merge (control). Both engines
# record the same phase *names* (templates and phase order are shared verbatim).
COMPLETED_PHASES = [
    "setup",
    "classify",
    "plan",
    "implement",
    "tests",
    "resolve",
    "e2e",
    "review",
    "patch",
    "document",
    "merge",
]

# The canonical v1 fields (the cross-language equivalence projection). These are
# exactly the keys the Python writer emits; the TS engine adds engine/runner/
# total_cost_usd on top.
V1_KEYS = [
    "adw_id",
    "schema_version",
    "issue_number",
    "issue_class",
    "branch_name",
    "base",
    "plan_file",
    "pr_number",
    "pr_url",
    "commit_message",
    "pr_body",
    "review_findings",
    "completed_phases",
]

# Keys the TS engine adds additively (PLAN.md D4); the Python reader drops them.
TS_ADDITIVE_KEYS = ["engine", "runner", "total_cost_usd"]


def _canonical_python_state() -> AdwState:
    """Rebuild the exact state the committed py-produced fixture was made from.

    Kept in lockstep with the generator so the drift guard is meaningful: if the
    writer or these values ever change without regenerating the fixture, the
    byte-compare fails.
    """

    state = AdwState(
        adw_id=ADW_ID,
        issue_number="5",
        issue_class="feat",
        branch_name="feat/5-00000000-cross-language-contract",
        base="main",
        plan_file="specs/5-cross-language-contract.md",
        pr_number=42,
        pr_url="https://github.com/kortiene/mx-agent/pull/42",
        commit_message="feat: cross-language state contract\n\ncloses #5",
        pr_body="Closes #5\n\nProves agents/{adw_id}/state.json round-trips across the py and ts engines.",
        review_findings=[
            {
                "severity": "blocker",
                "description": "example blocker the patch gate must fix",
                "location": "adw/_state.py:120",
            }
        ],
    )
    for phase in COMPLETED_PHASES:
        state.mark_done(phase)
    return state


def _v1_projection(doc: dict) -> dict:
    return {k: doc[k] for k in V1_KEYS if k in doc}


class CrossLanguageFixturePresenceTests(unittest.TestCase):
    def test_fixtures_exist(self) -> None:
        self.assertTrue(PY_FIXTURE.is_file(), f"missing {PY_FIXTURE}")
        self.assertTrue(TS_FIXTURE.is_file(), f"missing {TS_FIXTURE}")


class PythonFixtureDriftGuard(unittest.TestCase):
    """The py-produced fixture must be exactly what the real writer emits.

    Regenerate after an intentional change:
        python3 -c "from adw.test_cross_language_state import _regen; _regen()"
    """

    def setUp(self) -> None:
        self.tmp = tempfile.mkdtemp()
        patcher = mock.patch.object(_state, "AGENTS_DIR", Path(self.tmp))
        patcher.start()
        self.addCleanup(patcher.stop)

    def test_writer_output_matches_committed_fixture(self) -> None:
        state = _canonical_python_state()
        state.save()
        produced = state.state_path().read_text(encoding="utf-8")
        committed = PY_FIXTURE.read_text(encoding="utf-8")
        self.assertEqual(
            produced,
            committed,
            "py-produced fixture is stale; regenerate it (see the class docstring).",
        )


class TsFixtureLoadsThroughPythonReader(unittest.TestCase):
    """Criterion #2(ii): a TS-engine state.json loads+resumes under Python."""

    def setUp(self) -> None:
        self.tmp = tempfile.mkdtemp()
        patcher = mock.patch.object(_state, "AGENTS_DIR", Path(self.tmp))
        patcher.start()
        self.addCleanup(patcher.stop)
        # Stage the TS-produced fixture where AdwState.load() will find it.
        workspace = Path(self.tmp) / ADW_ID
        workspace.mkdir(parents=True)
        (workspace / _state.STATE_FILENAME).write_text(
            TS_FIXTURE.read_text(encoding="utf-8"), encoding="utf-8"
        )

    def test_v1_fields_survive_the_load(self) -> None:
        loaded = AdwState.load(ADW_ID)
        self.assertIsNotNone(loaded)
        assert loaded is not None
        self.assertEqual(loaded.adw_id, ADW_ID)
        self.assertEqual(loaded.schema_version, 1)
        self.assertEqual(loaded.issue_number, "5")
        self.assertEqual(loaded.issue_class, "feat")
        self.assertEqual(loaded.branch_name, "feat/5-00000000-cross-language-contract")
        self.assertEqual(loaded.base, "main")
        self.assertEqual(loaded.plan_file, "specs/5-cross-language-contract.md")
        self.assertEqual(loaded.pr_number, 42)
        self.assertEqual(loaded.pr_url, "https://github.com/kortiene/mx-agent/pull/42")
        self.assertEqual(loaded.commit_message, "feat: cross-language state contract\n\ncloses #5")
        self.assertEqual(
            loaded.pr_body,
            "Closes #5\n\nProves agents/{adw_id}/state.json round-trips across the py and ts engines.",
        )

    def test_resume_contract_intact(self) -> None:
        # Resume is driven entirely by completed_phases + the v1 fields, so a
        # cross-engine resume must see every phase as done and short-circuit.
        loaded = AdwState.load(ADW_ID)
        assert loaded is not None
        self.assertEqual(loaded.completed_phases, COMPLETED_PHASES)
        for phase in COMPLETED_PHASES:
            self.assertTrue(loaded.is_done(phase), f"resume would re-run {phase}")

    def test_blocker_finding_survives_for_the_patch_gate(self) -> None:
        # review_findings[].severity is load-bearing for patch_loop, so it must
        # round-trip across the language boundary.
        loaded = AdwState.load(ADW_ID)
        assert loaded is not None
        self.assertEqual(len(loaded.review_findings), 1)
        self.assertEqual(loaded.review_findings[0]["severity"], "blocker")

    def test_additive_keys_are_dropped_not_load_bearing(self) -> None:
        loaded = AdwState.load(ADW_ID)
        assert loaded is not None
        python_field_names = {f.name for f in fields(AdwState)}
        for key in TS_ADDITIVE_KEYS:
            self.assertNotIn(
                key,
                python_field_names,
                f"{key} must stay a TS-only additive key, never a Python dataclass field",
            )
            self.assertFalse(
                hasattr(loaded, key),
                f"Python reader must not surface the additive key {key!r}",
            )


class V1ProjectionEquivalence(unittest.TestCase):
    """Criterion #2(iii): the two engines agree on every v1 field."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.py_doc = json.loads(PY_FIXTURE.read_text(encoding="utf-8"))
        cls.ts_doc = json.loads(TS_FIXTURE.read_text(encoding="utf-8"))

    def test_v1_projections_are_identical(self) -> None:
        self.assertEqual(_v1_projection(self.ts_doc), _v1_projection(self.py_doc))

    def test_only_the_ts_doc_carries_additive_keys(self) -> None:
        for key in TS_ADDITIVE_KEYS:
            self.assertIn(key, self.ts_doc, f"ts fixture should carry additive key {key!r}")
            self.assertNotIn(key, self.py_doc, f"py fixture must not carry additive key {key!r}")

    def test_py_doc_has_exactly_the_v1_keys(self) -> None:
        self.assertEqual(set(self.py_doc), set(V1_KEYS))


class BothFixturesValidateAgainstSchema(unittest.TestCase):
    """Criterion #2(i): both engines' output validates against the contract."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    def test_py_fixture_validates(self) -> None:
        doc = json.loads(PY_FIXTURE.read_text(encoding="utf-8"))
        self.assertEqual(_validate(doc, self.schema), [])

    def test_ts_fixture_validates(self) -> None:
        doc = json.loads(TS_FIXTURE.read_text(encoding="utf-8"))
        self.assertEqual(_validate(doc, self.schema), [])


def _regen() -> None:
    """Regenerate the committed py-produced fixture from the real writer."""

    tmp = tempfile.mkdtemp()
    with mock.patch.object(_state, "AGENTS_DIR", Path(tmp)):
        state = _canonical_python_state()
        state.save()
        FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
        PY_FIXTURE.write_text(state.state_path().read_text(encoding="utf-8"), encoding="utf-8")
    print(f"wrote {PY_FIXTURE}")


if __name__ == "__main__":
    unittest.main()
